# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Restore Nugget Packages
- task: DotNetCoreCLI@2 
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: $(Build.SourcesDirectory)/nugget.config
# Run the build
- task: DotNetCoreCLI@2 
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
# Run your tests
- task: DotNetCoreCLI@2
  displayName: UnitTest
  inputs:
    command: test
    projects: '**/packtbookslibrary-api-Test.csproj'
    arguments: '--configuration $(buildConfiguration)'